import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import NextAuthProvider from "@/providers/NextAuth";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<head>
				<link rel="manifest" href="/manifest.json" />
			</head>
			<body>
				<NextAuthProvider>
					<Providers>{children}</Providers>
				</NextAuthProvider>
			</body>
		</html>
	);
}
