import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import NextAuthProvider from "@/providers/NextAuth";
import { Navigationbar } from "@/components/Navigationbar/Navigationbar";
import BottomBar from "@/components/BottomBar/BottomBar";
import { NextUiProvider } from "@/providers/NextUiProviders";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<head>
				<link rel="manifest" href="/manifest.json" />
			</head>
			<body>
				<NextAuthProvider>
					<Providers>
						<NextUiProvider>
						<Navigationbar />
						{children}
							<BottomBar />
						</NextUiProvider>
					</Providers>
				</NextAuthProvider>
			</body>
		</html>
	);
}
